//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use std::fmt::Debug;

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::models::media::MediaProvider;

#[derive(Clone, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default, TS)]
#[sea_orm(table_name = "users")]
#[serde(default)]
#[ts(export, rename = "User")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub username: String,
    pub provider_id: Option<String>,
    pub avatar_url: Option<String>,
    pub provider: MediaProvider,
    pub is_sandbox: bool,
    #[serde(skip_serializing)]
    pub access_token: Option<String>,
    #[serde(skip_serializing)]
    pub passcode: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Debug for Model {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("User")
            .field("id", &self.id)
            .field("username", &self.username)
            .field("provider_id", &self.provider_id)
            .field("is_sandbox", &self.is_sandbox)
            .field("access_token", &"[REDACTED]")
            .field("passcode", &"[REDACTED]")
            .field("created_at", &self.created_at)
            .field("updated_at", &self.updated_at)
            .finish()
    }
}
