//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::models::{
    media::MediaType,
    vault::{VaultDownloadType, VaultItemStatus},
};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "vault")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    #[sea_orm(unique)]
    pub destination_path: String,
    pub media_type: MediaType,
    #[sea_orm(column_type = "Text", nullable)]
    pub media_id: Option<String>,
    pub title: String,
    pub source_url: Option<String>,
    pub download_type: VaultDownloadType,
    pub status: VaultItemStatus,
    pub total_bytes: i64,
    pub downloaded_bytes: i64,
    #[sea_orm(column_type = "Float")]
    pub progress: f32,
    pub speed_bps: i64,
    pub eta_seconds: Option<i64>,
    pub temp_path: Option<String>,
    pub error_msg: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
