package processors

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strings"

	"komorebi-server/src/models"

	zlog "github.com/rs/zerolog/log"
	ffmpeg "github.com/u2takey/ffmpeg-go"
)

type Processor interface {
	Process(ctx context.Context, item models.VaultItem, outputDir string) error
}

var AllowedSubtitles = map[string]string{
	"subrip": "srt",
	"srt":    "srt",
	"vtt":    "vtt",
	"webvtt": "vtt",
	"ass":    "ass",
	"ssa":    "ass",
}

var RemuxProcessor = remux{}

func ProcessVideo(ctx context.Context, item models.VaultItem, outputDir string, startSegment int) error {
	if item.FilePath == "" {
		return errors.New("invalid file path")
	}
	err := RemuxProcessor.Process(ctx, item, outputDir, startSegment)
	if err != nil {
		return err
	}
	return nil
}

func ProcessSubtitle(ctx context.Context,
	item models.VaultItem, sub models.VideoSubtitle, outputDir string,
) error {
	ext := AllowedSubtitles[strings.ToLower(sub.Format)]
	if ext == "" {
		return errors.New("unsupported subtitle format")
	}

	input := item.FilePath
	outputFile := fmt.Sprintf("%s.%s", sub.Id.String(), ext)
	tempOutputFile := "temp_" + outputFile

	stream := ffmpeg.Input(input).
		Output(tempOutputFile, ffmpeg.KwArgs{
			"map": fmt.Sprintf("0:%d", sub.StreamIdx),
			"c:s": "copy",
		})
	stream.Context = ctx

	var stderr bytes.Buffer
	cmd := stream.OverWriteOutput().
		WithErrorOutput(&stderr).
		Compile()

	// Run inside the temp directory
	cmd.Dir = outputDir

	err := cmd.Run()

	zlog.Err(err).Str("file", input).
		Str("output", stderr.String()).
		Msg("ffmpeg subtitle extraction done")

	if err != nil {
		return err
	}

	// Rename it atomically when done
	err = os.Rename(filepath.Join(outputDir, tempOutputFile), filepath.Join(outputDir, outputFile))
	if err != nil {
		zlog.Err(err).Str("file", input).Msg("rename failed")
	}
	return nil
}

func BuildMasterPlaylist(item models.VaultItem) string {
	var builder strings.Builder
	builder.WriteString("#EXTM3U\n")
	builder.WriteString("#EXT-X-VERSION:7\n")
	builder.WriteString("#EXT-X-INDEPENDENT-SEGMENTS\n")

	audioMapped := 0
	for _, a := range item.AudioTracks {
		title := a.Title
		if title == "" {
			title = a.Lang
			if title == "" {
				title = fmt.Sprintf("Audio_%d", audioMapped+1)
			}
		}

		defaultFlag := "NO"
		if a.IsDefault {
			defaultFlag = "YES"
		}

		// FFmpeg maps audio to stream_1, stream_2, etc. (stream_0 is video)
		streamIdx := audioMapped + 1
		builder.WriteString(fmt.Sprintf(
			"#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID=\"a\",NAME=\"%s\",DEFAULT=%s,URI=\"stream_%d.m3u8\"\n",
			title,
			defaultFlag,
			streamIdx,
		))
		audioMapped++
	}

	builder.WriteString("#EXT-X-STREAM-INF:BANDWIDTH=5000000,AUDIO=\"a\"\n")
	builder.WriteString("stream_0.m3u8\n")
	return builder.String()
}

func BuildVODPlaylist(item models.VaultItem, streamName string) string {
	var builder strings.Builder
	builder.WriteString("#EXTM3U\n")
	builder.WriteString("#EXT-X-VERSION:7\n")
	builder.WriteString("#EXT-X-TARGETDURATION:10\n")
	builder.WriteString("#EXT-X-MEDIA-SEQUENCE:0\n")
	builder.WriteString("#EXT-X-PLAYLIST-TYPE:VOD\n")

	streamIdx := strings.TrimPrefix(streamName, "stream_")
	streamIdx = strings.TrimSuffix(streamIdx, ".m3u8")

	// Maps to init_X.mp4 style files generated by fmp4
	builder.WriteString(fmt.Sprintf("#EXT-X-MAP:URI=\"init_%s.mp4\"\n", streamIdx))

	totalSegments := int(math.Ceil(item.DurationSec / 10.0))
	for i := range totalSegments {
		dur := 10.0
		if i == totalSegments-1 {
			dur = item.DurationSec - float64(i*10)
		}
		builder.WriteString(fmt.Sprintf("#EXTINF:%.3f,\n", dur))
		// This tells the browser to request stream_0_0.m4s
		builder.WriteString(fmt.Sprintf("stream_%s_%d.m4s\n", streamIdx, i))
	}
	builder.WriteString("#EXT-X-ENDLIST\n")
	return builder.String()
}
