[env]
malClientId = ""
anilistClientId = ""
appEnv = "dev"
defaultHostedAuthPage = "https://p2kr.github.io/komorebi-web/auth.html"

[db]
path = "assets/main.sqlite?mode=rwc"
forceCreation = false
debug = true

[logger]
logLevel = "debug"
pretty = true
printConfig = true

[frontend]
staticPath = "../komorebi-web/build/"

[httpClient]
debug = false
curlCmd = true
