[env]
appEnv = "dev"
defaultHostedAuthPage = "https://p2kr.github.io/komorebi-web/auth.html"
vaultLoc = "vault"
port = "8081"

[db]
path = "assets/main.sqlite?mode=rwc"
forceCreation = false
debug = false

[logger]
logLevel = "debug"
pretty = false
printConfig = false
printCrawling = false

[frontend]
staticPath = "../static"

[httpClient]
debug = false
curlCmd = false
crawlerTimoutSec = "60s"

[torrentClient]
debug = false
